[workspace]
members = [
  "ark-client",
  "ark-core",
  "ark-grpc",
  "ark-rest",
  "ark-bdk-wallet",
  "e2e-tests",
  "ark-sample",
  "ark-rust-secp256k1-zkp",
  "ark-dlc-sample",
  "ark-rs",
]

resolver = "2"
